In [28]:
## Non-Linear Support Vector Regression (SVR)

In [29]:
# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [30]:
# Data preprocessing

# Importing the dataset
dataset = pd.read_csv('Position_salaries.csv')

# Matrix of features
x = dataset.iloc[:, 1:-1].values
print('Matrix of features: \n')
print(x)

# Dependent variable matrix
y = dataset.iloc[:, -1].values
print('Dependent variable vector: \n')
print(y)

# we need to change y into an 2D array because StandardScaler() expects 2D array
y = y.reshape(len(y),1)
print('Dependent variable vector in form of the 2D array: \n')
print(y)

Matrix of features: 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Dependent variable vector: 

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]
Dependent variable vector in form of the 2D array: 

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [31]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler() #two different objects because we fit the object to the variable and calculate mean and std dev

x = sc_x.fit_transform(x)
y = sc_y.fit_transform(y)

print('Scaled data - matrix of features: \n')
print(x)
print('Scaled data - dependent variable vector: \n')
print(y)

Scaled data - matrix of features: 

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]
Scaled data - dependent variable vector: 

[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]


In [32]:
# Train the model on the whole dataset (due to a small number of observations)

# building the model with radial basis kernel
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')

# .ravel will convert that array shape to (n, )
regressor.fit(x, y.ravel())

SVR()

In [33]:
# Predict the new result

sc_y.inverse_transform(regressor.predict(sc_x.transform([[6.5]])))


array([170370.0204065])

In [ ]:
# Visualise the SVR prediction results in low and high resolution

