In [3]:
## Data Preprocessing

## Import the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
## Import the dataset

dataset = pd.read_csv('Data.csv')

In [5]:
## Matrix of features (independent variables)

x = dataset.iloc[:,:-1].values

In [6]:
## Dependent variable vector

y = dataset.iloc[:,-1].values


In [7]:
## Missing data

import sklearn
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
## Encoding categorical data

## encode Country column in the matrix of features

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# make an instance of the class - object
# this object uses OneHotEncoder on first column and also returns other columns

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0] )], remainder = 'passthrough')

# connect object to the matrix of features

x = np.array(ct.fit_transform(x))

In [10]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [11]:
## encode dependent variable

from sklearn.preprocessing import LabelEncoder

# make an instance of the class LabelEncoder

le = LabelEncoder()

# connect object to the dependent variable

y = le.fit_transform(y)

print(y)


[0 1 0 0 1 1 0 1 0 1]
